services:
  xrpg-frontend:
    image: lehmann314159/xrpg-frontend:latest
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-https://xrpg-backend.verynormalserver.com}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://dungeon-crawler.verynormalserver.com}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true