version: '3'
services:
  xrpg-frontend:
    image: lehmann314159/xrpg-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BACKEND_URL=${BACKEND_URL:-https://dungeon-backend.verynormalserver.com}
    restart: unless-stopped